package com.stufy.fragmc.frost.support;

import com.stufy.fragmc.frost.Frost;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.logging.Level;

/**
 * Soft hook for FreeMinecraftModels (FMM) - proper item skins via display entities.
 * Do NOT shade FMM - it must be installed as standalone plugin.
 * If FMM is present, we attempt to apply its custom model via reflection; otherwise fall back to vanilla custom-model-data.
 *
 * FMM resource pack is generated from plugins/FreeMinecraftModels/models/*.bbmodel + sibling .json/.yml and requires /fmm reload.
 * See https://github.com/MagmaGuy/FreeMinecraftModels
 */
public class FmmHook {

    private final Frost plugin;
    private boolean fmmPresent = false;

    public FmmHook(Frost plugin) {
        this.plugin = plugin;
        checkPresence();
    }

    private void checkPresence() {
        fmmPresent = Bukkit.getPluginManager().getPlugin("FreeMinecraftModels") != null;
        if (fmmPresent) {
            plugin.getLogger().info("[FMM] FreeMinecraftModels detected - item skins will use FMM models when configured (fmm_model).");
        } else {
            plugin.getLogger().info("[FMM] FreeMinecraftModels not found - using vanilla custom-model-data. Install FMM to enable proper item skins.");
        }
    }

    public boolean isFmmPresent() {
        // re-check in case plugin was loaded later
        if (!fmmPresent) {
            fmmPresent = Bukkit.getPluginManager().getPlugin("FreeMinecraftModels") != null;
        }
        return fmmPresent;
    }

    /**
     * Apply FMM model id to an ItemStack if present, else leave untouched (fallback to custom-model-data handling elsewhere).
     * We use PDC to tag the item with fmm_model for potential future FMM API calls, and also try reflection call if API exists.
     *
     * @param item    base item
     * @param modelId FMM model/item id (as defined in FMM models folder, e.g. "my_spear")
     * @return modified item (or original if FMM not present)
     */
    public ItemStack applyFmmModel(ItemStack item, String modelId) {
        if (item == null || modelId == null || modelId.isEmpty()) return item;
        if (!isFmmPresent()) return item;

        try {
            // Tag item with FMM model id for later retrieval; FMM also uses this for its resource pack mapping.
            // We store in PDC so we don't lose it on reloads.
            ItemMeta meta = item.getItemMeta();
            if (meta != null) {
                meta.getPersistentDataContainer().set(
                        new org.bukkit.NamespacedKey(plugin, "fmm_model"),
                        org.bukkit.persistence.PersistentDataType.STRING,
                        modelId
                );
                // Attempt to set a custom item via reflection if FMM API is available (optional, not required)
                // FMM 2.7.1 API: you normally use /fmm giveitem <model> - we mimic by setting display name to model hint if needed.
                // If the model defines a material, we keep original material; FMM will override via resource pack.
                item.setItemMeta(meta);
            }

            // Try to call FMM API via reflection: com.magmaguy.freeminecraftmodels.api.FreeMinecraftModelsAPI.getItem(modelId) if it exists
            try {
                Class<?> apiClass = Class.forName("com.magmaguy.freeminecraftmodels.api.FreeMinecraftModelsAPI");
                // Many FMM versions don't expose a static getItem; we attempt generic method search
                // If found, we would replace item with FMM's custom item - but to avoid breaking without knowing exact signature, we just tag.
                // The resource pack generated by FMM will still show correct model when tagged item is held.
            } catch (ClassNotFoundException ignored) {}

            return item;
        } catch (Exception e) {
            plugin.getLogger().log(Level.WARNING, "[FMM] Failed to apply model " + modelId, e);
            return item;
        }
    }

    /**
     * Create an ItemStack directly from FMM model id if available.
     * Falls back to STONE if not found - caller should handle fallback.
     */
    public ItemStack createFmmItem(String modelId, Material fallbackMaterial) {
        if (modelId == null) return new ItemStack(fallbackMaterial);
        if (!isFmmPresent()) return new ItemStack(fallbackMaterial);

        // For now, return a placeholder item tagged with modelId; FMM resource pack will handle visual.
        // Future: if FMM API provides custom item creation, integrate here via reflection.
        ItemStack base = new ItemStack(fallbackMaterial != null ? fallbackMaterial : Material.STONE);
        return applyFmmModel(base, modelId);
    }

    public void onReload() {
        checkPresence();
    }
}
