name: Frost
version: 1.0.0
main: com.stufy.fragmc.frost.Frost
api-version: 1.21
depend:
  - Vault
softdepend:
  - Geyser-Spigot
  - Floodgate
commands:
  frost:
    description: Admin Frost command
    usage: /frost <reload>
    permission: frost.admin
  shop:
    description: Open the modifier shop
    usage: /shop
  equip:
    description: Open the equipment menu
    usage: /equip
  togglelock:
    description: Toggle hotbar lock
    usage: /togglelock
