name: Frost
version: 1.0.0
main: com.stufy.fragmc.frost.Frost
api-version: 1.21
depend:
  - Vault
softdepend:
  - Geyser-Spigot
  - floodgate
commands:
  frost:
    description: Admin Frost command
    usage: /frost <reload|setprofile|listprofiles|givecosmetic>
    permission: frost.admin
  shop:
    description: Open the cosmetics shop
    usage: /shop
  equip:
    description: Open the equipment menu
    usage: /equip
  togglelock:
    description: Toggle hotbar lock
    usage: /togglelock

permissions:
  frost.admin:
    description: Access to admin commands
    default: op
  frost.shop:
    description: Access to cosmetics shop
    default: true
  frost.equip:
    description: Access to equipment menu
    default: true
